src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less

-Problem is actual for ALL modal dialogs
-Issue origin: modal dialog when added to responsive manager can have different classes like _360-540, _540-720 etc; switching this classes changes modal dialog's width that immediately makes it belong to other resposive class, thus when changing viewport size you may see dialog changing it's width according to responsive class applied
-Fixed by making modal dialog styling  depend on body size

The Issue List dialog is not properly centered

---

src/main/resources/assets/admin/common/js/form/ValidationRecording.ts
src/main/resources/assets/admin/common/js/ui/KeyBindings.ts

-IE11 does not support iteration features of Map, in particular values() and keys() trigger errors in IE11; replaced with valid alternatives

IE11: Content Studio is blank #74

---

build.gradle

Fixed the problem of the compiled JS not present under the build folder, since `:processResources` task executes before the `gulpAll`.
**Comments on the problem:**
_When you run `gradle clean` locally it will only remove the `build/` folder. Our compiled files are placed under the `src/main/resources/**/common/js/` folder. They won't be removed with clean build. So the problem will occur even on local machine, if you have run the `gradle build` for the first time on newly cloned repo.
And the problem is that the `:processResources` task that copies all the source resources to `build/resources` runs before the `gulpAll` task, that compiles `.ts` and libs to `_all.js` files._

Fix build problems on Concourse for lib-admin-ui. #85

---

.travis.yml
build.gradle
gulpfile.js

Update Gulp `lint` task to emit errors when linting fails. Previously, there were only info messages and the build still succeeds.
Splited Gulp `all` into two: with lint and without.
Added Gradle `lint` task that is never UP-TO-DATE to be able to skip it.
Set `all:no-lint` default Gulp build task.
Updated Travis CI config to be more informative.

Fix linting

---

src/main/resources/assets/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
src/main/resources/assets/admin/common/js/app/wizard/WizardPanel.ts

Fixed bug with binding listeners to the wrong array: `validityManager`, instead of `wizardHeaderCreatedListeners`.
Optimized notifications for `name` and `displayName` fields from `WizardHeader` by wrapping them with `debounce`. This will prevent generating unwanted events when the key is constantly pressed or pressed very quickly, e.g. when deleting text with the backspace key.

Content wizard - Slow response when typing in the Display name field #267

---

src/main/resources/assets/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts
src/main/resources/assets/admin/common/js/data/PropertyArray.ts
src/main/resources/assets/admin/common/js/ui/selector/combobox/RichComboBox.ts

Added combobox selected options update from site configurator on `propertyArray` update.
Set `ignorePropertyChange` to `true` before updates to avoid cyclic `update` method calls, when multiple options are selected and updated.

Site Wizard - The list of selected applications is not refreshed after version rollback

---

src/main/resources/assets/admin/common/js/form/inputtype/combobox/ComboBox.ts

Fixed the problem with minification && SlickGrid filter compilation, when minified code was  transformed to the invalid filter function with RegExp.

Options in combobox are empty when mode is 'Prod' #419

---

build.gradle

Added excluded TinyMCE fonts to the distribution.

Icons are not displayed in `HtmlArea` on the mce-toolbar #426

---

src/main/resources/assets/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfigurator.ts

Added check for the absence of the pre-loaded options (when the combobox element has no selected options and there was no interaction with it).

Site wizard - application-view is not correctly updated in few cases #424

---

src/main/resources/assets/admin/common/styles/global.less

Removed page cropping and scroll absence (cases 2 & 3).
Height `100%` is set in the launcher (html).

Page content is cropped in the Page Editor #439

---

src/main/resources/assets/admin/common/js/ui/mask/Mask.ts

**First commit/solution:**
* Removed scroll animation, that must be replaced by pure CSS.
* Added click event propagation from masked element to sibling (mask) element to bypass `pointer-events: none` limitations.
**Second and final commit/solution:**
* Removed click propagation, since it is now handled in the masked element.

Page Component View is not scrollable when page is locked #435

---

src/main/resources/assets/admin/common/js/util/htmlarea/editor/HTMLAreaBuilderCKE.ts

-'code' moved to 'Format' list; 'blockquote' has complex logic and works via own plugin, unable to make it work in 'Format' list

CKEditor: move 'code' and 'blockquote' buttons to Format dropdown #531

---

src/main/resources/assets/admin/common/js/ui/menu/ActionMenu.ts
src/main/resources/assets/admin/common/styles/api/ui/menu/action-menu.less

…as unselected #575
Fixed invalid status class name ("expanded" to "down").
Added missing handlers.
**Additional:**
Fixed styles, by centering label text (between left border and dropdown). This will also prevent text from overflowing in some non-default languages (Russian, etc.).

Start/stop menu in the Application info panel won't close after switching to another application

---

src/main/resources/assets/admin/common/styles/api/util/htmlarea/modal-dialog.less

Updated Link and Search-and-Replace modal dialogs checkboxes to support long labels in different localizations.

Long checkbox labels float over the boxes

---

build.gradle

Fixed another missing dependency, that is loaded from the Live Edit.

CKEditor assets are not added to jar file #583

---

src/main/resources/assets/admin/common/js/content/resource/UpdateContentRequest.ts

-Before: saving unnamed content during update sends content's name as '__unnamed__' instead of '__unnamed__<unique_id>' it had before
-Now: sending unnamed content's name as is

Content Studio - Set content name as unnamed #603

---

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/ImageModalDialogCKE.ts
src/main/resources/assets/admin/common/lib/ckeditor/plugins/image2/plugin.js

-updated image plugin to set display to 'block' instead of 'inline-block' when centering image

Svg image in HTML editor disappears when center-aligned #632

---

src/main/resources/assets/admin/common/js/app/wizard/WizardPanel.ts
src/main/resources/assets/admin/common/js/app/wizard/WizardStepNavigatorAndToolbar.ts

Fixed issue, when orientation change didn't happen if help text button was absent.

Wizard Step navigator is partially visible in collapsed mode #643

---

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/LinkModalDialogCKE.ts

-CKE's getEditorAnchors() method returns all items duplicated; Filtering duplicated items on our side, not changing plugin itself

CKE: anchors are duplicated in the Insert Link dialog #654

---

src/main/resources/assets/admin/common/lib/ckeditor/plugins/image2/plugin.js

-Using figure tag to align images in editor instead of cke's wrapper element taht will be removed on save

CKE: in live edit cke's internal elements not removed when saving #670

---

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/LinkModalDialogCKE.ts

-Original link/anchor dialog has 2 dropdowns to pick anchor - by id and by name; We used 'by id', but it is not switching anchors; now using the one 'by name'

CKE: Can't change anchor link to point to another anchor #678

---

src/main/resources/assets/admin/common/js/form/inputtype/text/HtmlAreaCK.ts
src/main/resources/assets/admin/common/js/util/htmlarea/editor/HTMLAreaBuilderCKE.ts

-Not invoking editor's destroy when occurence removed
-Stopped triggereing selection change on blur as it seems to be not needed anymore

CKE: don't destroy editor if it's iframe was removed #693

---

src/main/resources/assets/admin/common/js/util/htmlarea/editor/HTMLAreaBuilderCKE.ts
src/main/resources/i18n/common.properties
src/main/resources/i18n/common_ru.properties

-using mouseover event to identify clickable elements
-to not modify editor's content using title attribute of editor's parent element (different for inline and regular mode) to display tooltip
Macro skipped because there are no tags wrapping it thus unable to identify when cursor is over macro.

Implement tooltip for macro, image, link and anchor in HTML Area #719

---

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/MacroModalDialog.ts

-CKEditor stripped off iframe when inserted as html; inserting macro as text now

HtmlArea - impossible to embed an <iframe> element in an HTML area #765

---

src/main/resources/assets/admin/common/js/form/set/FormSetView.ts

…p 2 items #759
-Dragged html elements are reloaded; HtmlArea needs to be reinitialized in that case and this happens with drag update event, but not with stop event when item remained in same position

Browser console errors when dragging HTML Area inside an ItemSet

---

src/main/resources/assets/admin/common/js/app/NamesAndIconView.ts
src/main/resources/assets/admin/common/js/content/ContentComboBox.ts
src/main/resources/assets/admin/common/js/content/ContentTreeSelectorItemViewer.ts
src/main/resources/assets/admin/common/js/content/_module.ts
src/main/resources/assets/admin/common/js/content/image/ImageSelectorViewer.ts
src/main/resources/assets/admin/common/js/content/resource/ContentTreeSelectorItem.ts
src/main/resources/assets/admin/common/js/dom/Element.ts
src/main/resources/assets/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
src/main/resources/assets/admin/common/styles/api/content/content-tree-selector-item-viewer.less
src/main/resources/assets/admin/common/styles/styles.less

* Fixed the default ContentComboBox viewer, removing `any` typecast to the ContentSummaryViewer.
* Fixed toolbar position.
* Added additional check for the empty parent in case of its absence.

Update combo box viewers

---

build.gradle
gradle.properties
settings.gradle

Update publish configuration to use new version of `app-defaults`, `maven-publish` plugin and `publish` command, instead of maven and `uploadArchives`.
Fixed TIMEOUT exception, when resolving dependencies.
*IMPORTANT:* PR should be merged, when [gradle-defaults v1.1.0](https://github.com/enonic/gradle-defaults/issues/1). is published.

Update publish configuration #807

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-There's keybinding on 'enter' key set in TreeGrid that is shelved when modal dialog is open; When closing modal dialog with enter key and unshelving previous keybindings (including 'enter' handler) enter event is triggered immediately, seems because it is setup to be triggered on KEYUP. Fixed by setting treegrid's enter handler on keydown

ConfirmationDialog - wrong behavior for "Enter"-key #818

---

src/main/resources/assets/admin/common/js/locale/Locale.ts
src/main/resources/assets/admin/common/js/ui/locale/LocaleComboBox.ts
src/main/resources/assets/admin/common/js/ui/locale/LocaleViewer.ts

-Three non-conforming locales must be treated as special cases. These are ja_JP_JP, th_TH_TH, nn_NO_NY. Last one have been breaking locale dropdown because it has same 'nn_NO' locale tag as a regular nn_NO locale

Content Wizard - error in language selector #857

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeRoot.ts

* Added check for the selection modification type, to prevent multiple selection updates notification, even when the selection hasn't changed.
* Added check for the previous selection modification type to show notification, when the selection was removed.
* Removed obsolete checks for newly selected content.

Browse toolbar is not refreshed when selected contents have been deleted #911

---

src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeSingleOccurrence.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts

-Issue occurs because of unbind listeners in property/propertyarray after live edit reload. Issue origin in InputOccurrenceView and BaseInputTypeManagingAdd, but also updated BaseInputTypeSingleOccurrence and FormSetOccurrenceView in advance

Incorrect behavior after applying changes in Inspection Panel #918

---

src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts
src/main/resources/assets/admin/common/js/ui/dialog/ConfirmationDialog.ts
src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
src/main/resources/assets/admin/common/js/ui/mask/Mask.ts

-Divided modal dialog constructor init process to several phases:
1. Initializing variables (initElements() method), pure vars initialization
2. Doing actions not related to vars initializing, like setting click ignored element or setting element to focus on open or whatever that is supposed to be done after elements initialized (postInitElements() method)
3. Initializing event listeners (initListeners() method)
-Moved dom related actions, like appendChild() or addClass(), to doRender()
-Added mask/unmask methods to remove hardcoded addClass('masked')
-Added setElementToFocusOnShow() to set focus on correct element when dialogs is opened, taking into account if dialog is already rendered or not
-Saving dialog config in var

Refactoring of modal dialogs

---

src/main/resources/assets/admin/common/styles/api/ui/mask.less

Hid overflow to prevent spinner to be visible, even when the load mask has zero width, which may result in wrong calculations.

Site Wizard - broken layout after selecting a controller #947

---

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/js/form/set/itemset/FormItemSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/itemset/FormItemSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/itemset/FormItemSetView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

* Added `lazyRender` status passing from one `FormItemLayer` to another through `FormItemSetOccurrenceView`, just like through the `FieldSetView` or `FormOptionSetOptionView`.

Item-set inside part config is not properly rendered in the Inspect panel #955

---

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts

-Moving load mask show/hide related code out of dialogs to their common parent
-Showing modal dialog only when dialog is rendered and shown, otherwise waiting for dialog to be shown

Handle loading mask in the base ModalDialog class

---

src/main/resources/assets/admin/common/js/ui/selector/dropdown/Dropdown.ts

* Updated `selectRow` to not change the focus when the row is selected. `silent = false` is used by default most of the time but in some cases, like in `WidgetsSelectionRow` update, the previously selected row is restored in silent mode, which should not result in a focus change.

Display name field no longer gets focus in the new content wizard #969

---

src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

Fixed so form sets get correctly updated after content is saved.
Issue is with how we store option set data and how it is set in wizard; when option set is created (during layout() invocation) in wizard it adds empty property set for each option available to be chosen (that is not saved if option is not selected), but that doesn't happen after content is saved/updated

OptionSet wizard - Incorrect behavior of validation #983

---

src/main/resources/assets/admin/common/js/security/IdProviderConfig.ts
src/main/resources/assets/admin/common/js/util/PropertyTreeHelper.ts
src/main/resources/assets/admin/common/js/util/_module.ts

Moving PropertyTreeHelper.ts from contentstudio to lib-admin-ui thus any app could use it.

Move PropertyTreeHelper from CS to lib-admin-ui

---

src/main/resources/assets/admin/common/js/content/ContentPath.ts

-fromParent() method operates directly on parent's array of elements instead of making copy, thus parent's elements array gets modified when creating ContentPath instance using this method

ContentPath class has problem with fromParent() method #1014

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

…wizard. #1039
-Issue was that highlighted node was pointing to outdated treenode in certain conditions (in filtered root after filtering treenodes are recreated), thus all nodes updates were updating actual tree nodes but not a highlighted one and all actions state checks were performed on that outdated treenode. Fixed by resetting highlighted node on data init

Highlighted node in Tree grid is not reset on data refresh

---

src/main/resources/assets/admin/common/styles/api/ui/treegrid/tree-grid.less

-SlickGrid structure changed after latest update, need to reflect those changes in css

Scrollbar in the tree grid is not taking full available height #1043

---

src/main/resources/assets/admin/common/js/dom/ElementHelper.ts
src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less

* Updated overflow update, making element to use the default one (auto), until the debounced handler does not update it.
* Updated ModalDialog to use CSS classes, instead of setting properties directly.
* Refactored resize handlers.

Handle overflow in modal dialogs on page resize

---

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts

…n Publishing Wizard #1078
Added `onResize` handler, even if `ResizeObserver` is present, since the resize handler is optimized and may cover some resize handlers in this case.

Incorrect overflow behaviour inside modal dialog after resize

---

src/main/resources/assets/admin/common/js/data/PropertySet.ts

…ection #1112
-Cleaning empty values wasn't working properly: if empty property was not on root level it was not removed

PropertySet is not cleared properly

---

src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts

-Combobox has incorrect behaviour - when there's something typed in it's input and apply/enter pressed then input's value gets reset with empty string '', that triggers unwanted loader requests on closed combobox dropdown
-In case of image selector: enter/apply on filtered combobox triggers slickgrid's update that goes into infinite cycle because of our gallery mode logic
-Fixed via resetting input's value silently

Error after selecting an option in Image Selector

---

src/main/resources/assets/admin/common/lib/slickgrid/slick.grid.js

-Navigation in gallery mode broke after latest slickgrid update

Image Selector - keyboard navigation doesn't work in flat mode #1138

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-Maintaining list of expanded nodes, thus after grid is reloaded it's nodes that will be loaded on scroll will be expanded if needed

Selected item loses selection after grid refresh #1148

---

src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts
src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts

Issue origin: dialog can be spawned within other parent dialog without notifying it (e.g. in SiteConfiguratorDialog), so when handlers that check if user clicked out of a parent dialog invoke `hasSubDialog()` it returns false meanwhile other dialog is open, thus focus starts jumping between these 2 open dialogs.
Solved by updating modal dialog and keeping trace of open dialogs independently:
1. Added class with static methods (DialogManager) that will hold list of open dialogs and will notify on new dialog opened. Any class can use it to listen for dialog open event or check number ot total open dialogs
2. Modal dialog will update DialogManager on opening and closing
3. Added modal dialog state enum (OPEN|CLOSED) so now you could use `isOpen()` method instead of `isVisible()` for dialog. …

Fix handling of child dialogs spawned by a modal dialog

---

src/main/resources/assets/admin/common/js/dom/Body.ts

…ave #1157
-Issue is related to https://github.com/enonic/lib-admin-ui/issues/283, we used to do a trick with switching positions of head and body elements to keep `<head>` element first within it's `<html> `parent, however moving head makes all resources placed in head, including css, reload and that makes page reapply styles when they are loaded; restoring highlighted selection is invoked during resources load, thus position of highlighter is calculated before styles applied and gets shifted after reload
-Solved by moving` <body>` element instead of `<head>`

Fix the way <head> element is added to the HTML document

---

src/main/resources/assets/admin/common/js/ui/DragHelper.ts

Replaced `DragHelper` root instance with the local (document).
When the instance of the `DragHelper` was passing to the drag handlers in the iframe, the handlers were evaluating the scrollableParent incorrectly, using root `document`, instead of the one from an iframe.

Draggable plugin is called in the wrong context #1181

---

src/main/resources/assets/admin/common/js/ui/selector/dropdown/Dropdown.ts

Removed the function call from StringHelper, since the first expression will do the same checks. Also call of the static methods, that uses webpack module system after compile are not compatible with evaluated filter function of the SlickGrid.

Console errors when applying filter in Page Controller selector #1186

---

src/main/resources/assets/admin/common/js/app/NamesAndIconView.ts
src/main/resources/assets/admin/common/js/app/NamesView.ts
src/main/resources/assets/admin/common/js/app/view/ItemStatisticsHeader.ts
src/main/resources/assets/admin/common/js/dom/AEl.ts
src/main/resources/assets/admin/common/js/dom/BEl.ts
src/main/resources/assets/admin/common/js/dom/IEl.ts
src/main/resources/assets/admin/common/js/dom/SpanEl.ts
src/main/resources/assets/admin/common/js/ui/button/Button.ts
src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts

Removed unsafe `setHtml(*, false)` calls without html escaping. 
Added additional `fromText` methods to the text elements (`<span>`, `,<b>`, etc.) to create element with text inside.

Add escape for all unsafe data, passed to setInnerHtml method #1145

---

package-lock.json
src/main/resources/assets/admin/common/js/ui/uploader/UploaderEl.ts
src/main/resources/i18n/common.properties

…d pictures and files #1198
Set option that was added in the new version of the file uploader (`requireSuccessJson`) to `false`, since we don't follow specific JSON response scheme and don't add `success` parameter to that JSON, absence of which has lead to request treated as failed fy the library.
Added localization for attachment upload success and failure.

UploaderEl doesn't correctly process response of upload operation

---

src/main/resources/assets/admin/common/js/data/ValueTypeBoolean.ts
src/main/resources/assets/admin/common/js/form/inputtype/checkbox/Checkbox.ts
src/main/resources/assets/admin/common/js/ui/Checkbox.ts
src/main/resources/assets/admin/common/js/ui/RadioGroup.ts

Changed `Checkbox.updateProperty` to reset dirty state instead of updating property value. Changed default value of a boolean value type to `false` instead of null. Removed `onChange` event handlers of Checkbox and Radiogroup inputs since they are doing the same as FormInputEl's `onChange` handler

Save button remains enabled after checkbox state is changed and content is saved (#1463)

---

src/main/resources/assets/admin/common/js/ui/uploader/UploaderEl.ts

-Not letting uploader send more than 1 request simultaneously, otherwise when sending multiple items result is unpredictable

Limit max allowed concurrent requests by uploader #1227

---

src/main/resources/assets/admin/common/js/app/wizard/WizardStepForm.ts
src/main/resources/assets/admin/common/js/ui/dialog/ConfirmationDialog.ts
src/main/resources/i18n/common.properties
src/main/resources/i18n/common_es.properties
src/main/resources/i18n/common_fr.properties
src/main/resources/i18n/common_no.properties
src/main/resources/i18n/common_pl.properties
src/main/resources/i18n/common_pt.properties
src/main/resources/i18n/common_ru.properties
src/main/resources/i18n/common_sv.properties

-NB: Had to move addAction() calls into initElements(), otherwise if triggered after ModalDialog's open() key bindings won't be set

Refactor usage of save confirmation dialog #1229

---

package-lock.json
src/main/resources/assets/admin/common/js/dom/LabelEl.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
src/main/resources/assets/admin/common/js/ui/RadioButton.ts
src/main/resources/assets/admin/common/js/ui/RadioGroup.ts

* Updated `RadioButton` and `RadioGroup` to be customizable.
* Moved `RadioButton` to the separate file.
* Refactored `RadioButton`, making it receive config object instead of a lot of properties.
* Made it posible to pass the label element instead of a string to the `RadioButton`.

Make RadioGroup and RadioButton extendable #1242

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-Parent node we're inserting childe to could be not selected or highlighted at all, so no need to reselect it

Parent node gets selected after a child node added to the grid

---

src/main/resources/assets/admin/common/js/app/wizard/WizardPanel.ts
src/main/resources/assets/admin/common/js/app/wizard/WizardStepNavigatorAndToolbar.ts
src/main/resources/assets/admin/common/js/ui/panel/SplitPanel.ts

-Triggering resize handler only after elements rendered, also using debounce whenever possible (can't use it for navigator toolbar since it must be updated immediately on resize)

Incorrect layout in Wizard Step Navigator Toolbar #1267

---

src/main/resources/assets/admin/common/js/app/browse/BrowsePanel.ts
src/main/resources/assets/admin/common/js/ui/grid/Grid.ts
src/main/resources/assets/admin/common/js/ui/grid/GridSelectionHelper.ts
src/main/resources/assets/admin/common/js/ui/selector/DropdownTreeGrid.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeGridSelection.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeRoot.ts
src/main/resources/assets/admin/common/js/ui/treegrid/actions/SelectionController.ts
src/main/resources/assets/admin/common/js/ui/treegrid/actions/SelectionPanelToggler.ts

-Keeping list of selected data items ids, NOT node ids. Thus no need to keep list of current and stashed selection and filter duplicated nodes when getting selected nodes
-BrowsePanel: treeNodesToBrowseItems -> dataItemsToBrowseItems since only node data was used in browse panels
-Left 1 function to deselect all rows instead of 3!
-RootNode and TreeNode is internal grid structure thing, should not be exposed to non-inheritors; Updated so non-inheritors get data items directly instead of nodes (most of them just needed to count items). Still a lot to be done

Browse toolbar is not updated after deleting filtered content #1273

---

src/main/resources/assets/admin/common/js/ui/menu/TreeContextMenu.ts

-Not stopping event propagation so DOM elements in IE receive click events

[IE 11] Page Component View is not reacting on click #1308

---

src/main/resources/assets/admin/common/js/ui/selector/dropdown/Dropdown.ts

When Dropdown is in the Form with validation enabled, clicking on dropdown handle may create a focus loss, which will cause the validation and focus switch to the empty fields, that should not be empty.

Fix focus loss on dropdown handle click

---

src/main/resources/assets/admin/common/js/ui/dialog/ConfirmationDialog.ts

Added `yes-button` and `no-button` classes for styling.
Added `setQuestion` param to pass unescaped text to confirmation body.

Add button classes to Confirmation dialog

---

src/main/resources/assets/admin/common/js/ui/button/MenuButton.ts
src/main/resources/assets/admin/common/js/ui/menu/ContextMenu.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

Fixed:
* Menu button's dropdown not closing on a click outside
* Context menu constantly listening to click event on Body
* Tree grid constantly listening to click event on Body to remove highlighting
* Tree grid losing selection on a click outside of expanded Publish button's dropdown(f.ex. toolbar)

Menu button dropdown won't close on a click outside

---

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts

-using option label as a search target instead of name

Filtering of options with white spaces is not working in OptionSet #1700

---

src/main/resources/assets/admin/common/js/query/FulltextSearchExpression.ts
src/main/resources/assets/admin/common/js/query/PathMatchExpression.ts

-Escaping `+ - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /` symbols mentioned in https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters to prevent backend errors

Sanitise content queries search string

---

src/main/resources/assets/admin/common/js/query/PathMatchExpression.ts

…not working in Image Selector #1846
-Replacing white spaces in the search string with wildcard to handle cases:
1. When content has path where spaces in display name are represented with '-' symbol
2. When spaces in path are multiple (E.g. path like "/content/features/date   time")
The only drawback is in potential extra hits due to wildcard usage

Filtering selector by parent display name doesn't work if the name contains spaces

---

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts
src/main/resources/assets/admin/common/js/form/FormItemView.ts
src/main/resources/assets/admin/common/js/form/FormView.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
src/main/resources/assets/admin/common/styles/api/form/set/optionset/form-option-set-view.less

-Issue was in updating items for option set views: we clear totally data/properties for non-selected options on save and it's children items were not updated correctly since no props were provided
-Refactored create/update logic to remove redundant code

Option Set - Incorrect radio button behavior in multi selection #1878

---

src/main/resources/assets/admin/common/js/form/FormOccurrenceDraggableLabel.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/itemset/FormItemSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewMultiOptions.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewSingleOption.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
src/main/resources/assets/admin/common/js/ui/selector/dropdown/Dropdown.ts
src/main/resources/assets/admin/common/js/ui/selector/dropdown/SelectedOptionView.ts

-FormOptionSetOccurrenceView was refactored and descendants were created to differentiate between
single/multi selection options and to avoid pervasive usage of isSingleSelection check
-FormSetOccurrenceView was refactored to divide form items layout and instantiation of it's own required elements
-Removed duplicated code

Invalid Option Set is not highlighted when saved in a new content

---

src/main/resources/assets/admin/common/js/form/inputtype/text/TextInputType.ts

-That affects comparing persisted and actual data: if persisted item data has trailing spaces then form data comparison will fail due to trim

TextInput: don't trim value #1988

---

src/main/resources/assets/admin/common/js/ui/NamesAndIconViewer.ts
src/main/resources/assets/admin/common/js/ui/selector/OptionsTreeGrid.ts
src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts
src/main/resources/assets/admin/common/js/ui/selector/combobox/RichSelectedOptionView.ts
src/main/resources/assets/admin/common/styles/api/app/names-and-icon-view.less
src/main/resources/assets/admin/common/styles/api/ui/grid/grid.less
src/main/resources/assets/admin/common/styles/api/ui/names-and-icon-viewer.less
src/main/resources/assets/admin/common/styles/api/ui/selector/combobox/combobox.less
src/main/resources/assets/admin/common/styles/api/ui/selector/combobox/rich-combobox.less
src/main/resources/assets/admin/common/styles/api/ui/selector/combobox/selected-options.less
src/main/resources/assets/admin/common/styles/api/ui/selector/dropdown/dropdown.less
src/main/resources/assets/admin/common/styles/api/ui/treegrid/tree-grid.less
src/main/resources/assets/admin/common/styles/main.less
src/main/resources/assets/admin/common/styles/main.lite.less

-Height of a slickgrid's row must not be set via css/less but via internal slickgrid rowHeight param, we have setRowHeight in grid options object for it
-Using display: flex for grid cells and its' children elements wherever possible
-Moved common slick-cell styling to a grid.less and removed duplicated entries in other places
-Added separate names-and-icon-viewer.less for NamesAndIconViewer.ts styling
-Adjusted corresponding selected-options styling

Increase height of selector dropdowns #1993

---

src/main/resources/assets/admin/common/js/security/auth/IsAuthenticatedRequest.ts

-Using cache in auth request to prevent extra requests. Can be removed any time when auth meta will be propagated into live session

IsAuthenticatedRequest: cache LoginResult? #1648

---

tsconfig.dev.json

Inlined sources, so the compiled JS files could be used as 3rd party libraries in other projects.

Investigate and fix the sourcemaps #1836

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-helping slickgrid to redraw it's items on resize

Browse panel gets empty after clicking on Show/Hide Search Panel #2083

---

src/main/resources/assets/admin/common/js/ui/Checkbox.ts

Checkbox is now created from the InputEl, which simplifies the code and fixes `setName` method.
Fixed `setValue` and `getValue` calls to set value in form properly.
Added name value to the builder.

Checkbox is not working as form input element #2243

---

src/main/resources/assets/admin/common/js/form/FormContext.ts
src/main/resources/assets/admin/common/js/form/InputView.ts
src/main/resources/assets/admin/common/js/form/InputViewValidationViewer.ts
src/main/resources/assets/admin/common/js/form/inputtype/InputTypeView.ts
src/main/resources/assets/admin/common/js/form/inputtype/InputValidationRecording.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputType.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/OccurrenceValidationRecord.ts
src/main/resources/assets/admin/common/styles/api/input-common.less

-Added isValidationErrorToBeRendered to InputTypeView to move InputView related logic (to render or not render validation error) to it. 
-Cleaned InputValidationRecording from validationErrorToBeRendered and validationMessageToBeRendered that are totally do not belong to this class
-Added hideValidationDetailsByDefault to InputTypeView to let input type decide rather to show or not validation details under each input by default
-Updated validation details toggler
-Showing custom validation errors for each input occurrence
-Using styles wherever possible to handle show/hide of validation

Support custom validation errors for input types #2262

---

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts
src/main/resources/assets/admin/common/js/form/FormItemLayerFactory.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts
src/main/resources/assets/admin/common/js/form/FormItemView.ts
src/main/resources/assets/admin/common/js/form/FormView.ts
src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/js/form/set/fieldset/FieldSetView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

-regression issue from fix of https://github.com/enonic/lib-admin-ui/issues/1964
-Added validateOccurrenceOnAdd param to let form items with occurrences toggle validation of newly added occurrences on demand

New ItemSet occurrence gets instantly validated #2333

---

src/main/resources/assets/admin/common/js/form/HelpTextContainer.ts
src/main/resources/assets/admin/common/js/form/set/FormSetHeader.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

-Showing FieldSetView's own help text also

'Show all help texts' icon doesn't work for sets #2392

---

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-Modal Dialog: letting override adding 'right' and 'left' shortcuts
-Treegrid:
--letting override creation of the navigation shortcuts
--exposing navigation up and down to inheritors
--fixing issue in 'onLeftKeyPress' and in 'onRightKeyPress' with casting row number to a boolean
--fixing 'onEnterKeyPress' and making it work when there are also selected items
--exposing 'selectRow()' to inheritors

treegrid_modal_dialog_upd

---

src/main/resources/assets/admin/common/js/ui/grid/Grid.ts
src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseRichComboBox.ts
src/main/resources/assets/admin/common/js/util/loader/BaseLoader.ts

* Calculate scrolled distance inside dropdown on `loaded` and `scroll` events instead of using `setInterval`
* Don't trigger `loaded` event in `BaseLoader` if data hasn't changed
* Support forced reload in `BaseRichComboBox`

Fix lazy loading in BaseRichCombobox

---

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

-Issue origin is from updating wizard after check for permissions to modify content is over and as modify is allowed it allows to enable all inputs after layout is already over and some checkboxes are intentionally disabled to prevent breaking options limit

Multi-select option-set allows selecting more than maximum options #2513

---

src/main/resources/assets/admin/common/js/ui/selector/OptionsTreeGrid.ts
src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-resetting active grid cell after click on expand/collapse

Expanded node gets highlighted in Content Selector #1998

---

src/main/resources/assets/admin/common/js/app/bar/AppBar.ts
src/main/resources/assets/admin/common/js/app/bar/AppIcon.ts
src/main/resources/assets/admin/common/js/app/bar/TabbedAppBar.ts

@ashklianko 
Does it makes sense to let the app icon be reachable by keyboard if it does contain any action? 
This PR allows that. It was the behavior requested by Thomas Heartman in this [issue](https://github.com/enonic/app-users/issues/647)
If we don't want to allow that, i.e, only make app icon reachable by keyboard if there is an action attached to it, then we'll need to move line 20 to inside the conditional on line 22.

Added keyboard accessibility to AppIcon

---

src/main/resources/assets/admin/common/styles/api/input-common.less

@alansemenov 
is it ok to use setTimeout as I did in this case? Doesn't seems right, but does the trick. 
The thing is that I need to execute `adjustHelpTextPadding` only after not only the parents are rendered, but also the child ones. What's the best way to do that?
Also, 100px of right padding is enough space for a counter of `<= 9999` characters, because 5 digits would overlap again. Should we take care of 5 digits?

Help Text right padding if show counter is true (#2594)

---

src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts

-found a flaw in the isDropdownShown() method, reproduced when combobox is located within modal dialog

Modal dialogs: comboboxes remain open after reopening dialog #2650

---

src/main/resources/assets/admin/common/js/security/PrincipalLoader.ts
src/main/resources/assets/admin/common/js/util/loader/BaseLoader.ts

Compare search results with previously filtered dataset instead of the full one

Can't reset search string in BaseLoader

---

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts
src/main/resources/assets/admin/common/js/form/FormOccurrenceDraggableLabel.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/styles/api/form-common.less
src/main/resources/assets/admin/common/styles/api/form/set/form-set-view.less
src/main/resources/assets/admin/common/styles/api/form/set/optionset/form-option-set-view.less

* Inverted rendering logic of an item/option-set occurrence: it will be created as collapsed by default and won't be added to DOM until expanded.
* Fixed a new item-set occurrence briefly showing "_undefined_" in its title
* Styling fixes

Optimise performance of item-/option-set rendering

---

src/main/resources/assets/admin/common/js/form/FormContext.ts
src/main/resources/assets/admin/common/js/form/inputtype/InputValidationRecording.ts
src/main/resources/assets/admin/common/js/form/inputtype/combobox/ComboBox.ts
src/main/resources/assets/admin/common/js/form/inputtype/principal/PrincipalSelector.ts
src/main/resources/assets/admin/common/js/form/inputtype/radiobutton/RadioButton.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputType.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeSingleOccurrence.ts

-BaseInputTypeManagingAdd didn't implement taking care of a custom validation errors, fixing it
-Most of the BaseInputType.ts inheritors use context object and read config out of it; moved context and readConfig() to their common parent

Custom validation is not working for Selector inputs #2701

---

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts

-highlighting node that is already present in the tree, expanding parents to it on demand

TreeGrid: add public API method to highlight/unhighlight items #2743

---

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewSingleOption.ts

Don't expand selected option in a collapsed option-set.

Multiple occurrences of an option-set should not be auto-expanded

---

src/main/resources/assets/admin/common/js/application/ApplicationConfig.ts
src/main/resources/assets/admin/common/js/form/FormItemLayer.ts
src/main/resources/assets/admin/common/js/form/FormItemLayerFactory.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrence.ts
src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts
src/main/resources/assets/admin/common/js/form/FormItemState.ts
src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfigProvider.ts
src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
src/main/resources/assets/admin/common/js/form/set/itemset/FormItemSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewSingleOption.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrences.ts
src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts

-Populating property array of a FormOptionSetOptionView with a default selected options on add -Adjusted constructor props of ApplicationConfiguratorDialog -Removed redundant code that was selecting default option -Added new param "isNew" to FormItemLayer indicating that a FormItem is newly added (can be item in just created content, can be added via user action, can be item in the app configuration form or in inspection panels)

Preselection of options inside option-set doesn't work in site.xml #2797

---

src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts

Passed the correct html element (previously it was calculated to the child).

Sortable state can not be disabled #2895

---

src/main/resources/assets/admin/common/js/ui/form/Validators.ts

As requested, url query params with only "key" (i.e, without "value") are now valid.

Fix key-value url regex #3113

---

package.json

Fixed swc/cli stopped dropping leading path from v0.3.0.

SWC upgrade breaks dev build #3461

---

src/main/resources/assets/admin/common/js/dom/FormInputEl.ts

Restored `oldValue` to default empty string.

OriginalValue has invalid initial value #3509

---

src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts
src/main/resources/assets/admin/common/js/ui/selector/list/FilterableListBoxWrapperWithSelectedView.ts

Also:
* fixed the same issue for Owner dropdown
* fixed a bug when selected option won't get deleted for the next selected content
* set focus inside the filter once selection is removed

Language field keeps previous search

---

src/main/resources/assets/admin/common/js/ui/selector/list/TreeListBox.ts

- calc level more efficiently
- tree list elements always supposed to have a parent list

TreeListBox: data-level attribute is not set #3981

---

src/main/resources/assets/admin/common/styles/api/form-common.less
src/main/resources/assets/admin/common/styles/api/ui/help-text.less
src/main/resources/assets/admin/common/styles/main.less
src/main/resources/assets/admin/common/styles/main.lite.less

- Leaving help-text container as it is to not break backward compatibility

Help text: move related styles to a separate .less file  #4021

---

.github/workflows/gradle.yml
.github/workflows/release.yml
build.gradle
package.json
pnpm-lock.yaml

Switched Java from 11 to 21, as the most recent Java used by apps.
Removed unused dependencies (were added by mistake from Enonic UI epic)

Upgrade Java version

---

src/main/resources/assets/admin/common/js/form/inputtype/time/DateTime.ts
src/main/resources/assets/admin/common/js/form/inputtype/time/DateTimeRange.ts
src/main/resources/assets/admin/common/js/ui/time/DateTimePicker.ts
src/main/resources/assets/admin/common/js/ui/time/DateTimePickerPopup.ts
src/main/resources/assets/admin/common/js/ui/time/DateTimeRangePicker.ts
src/main/resources/assets/admin/common/js/ui/time/TimePickerPopup.ts
src/main/resources/assets/admin/common/js/util/DateHelper.ts
src/main/resources/assets/admin/common/js/util/DateTime.ts
src/main/resources/assets/admin/common/js/util/Timezone.ts

- TimePickerPopup now uses selected date's offset (+ 1 for wintertime and +2 for summertime)
- Key change is to stop using today's date timezone offset as default and to use the offset value of the selected date. The issue was that when parsing and initializing saved DateTime value (which is saved in UTC format, '2025-09-15T12:00:00Z' for example) we've been using TODAY's date offset and not the one from the actual value

Time is incorrectly displayed for DateTime input with timezone #4144
