src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
Fixed post load not enabling after sequential hide & show event.
=> Fix post load in grid not being enabed after sequential hide & show event #27

src/main/resources/assets/admin/common/js/_module.ts, src/main/resources/assets/admin/common/js/form/inputtype/text/HtmlArea.ts, src/main/resources/assets/admin/common/js/lib/ckeditor.d.ts, src/main/resources/assets/admin/common/js/liveedit/text/TextComponentView.ts, src/main/resources/assets/admin/common/js/util/htmlarea/editor/HTMLAreaBuilder.ts, src/main/resources/assets/admin/common/lib/_include.js, src/main/resources/assets/admin/common/styles/api/util/htmlarea/html-area.less
-Required configuration so CKEditor can be used on html page
=> Add integration with CKEditor (Content Wizard) #33

src/main/resources/assets/admin/common/js/form/ValidationRecording.ts, src/main/resources/assets/admin/common/js/ui/KeyBindings.ts
=> IE11: No background image on login page #76

src/main/resources/assets/admin/common/js/ui/dialog/ProgressBarManager.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts, src/main/resources/assets/admin/common/styles/api/app/move-content-dialog.less, src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less, src/main/resources/assets/admin/common/styles/api/ui/dialog/progress-bar-manager.less, src/main/resources/assets/admin/common/styles/apps/content/dialog/dependant-items-dialog.less
* Updated styles of processing message that is above the progress bar.
* Added possibility to disable `ComboBox` controls.
* Moved `lock` class to modal dialog to be able to stylize all locked modal dialogs.
=> Show progress bar while the content is being moved #208

src/main/resources/assets/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts, src/main/resources/assets/admin/common/js/ui/text/TextInput.ts
Added possibility to automatically trim the white spaces on focus/blur and on demand.
=> Users App - trim spaces in displayName input (Wizards) #254

src/main/resources/assets/admin/common/js/form/inputtype/text/HtmlArea.ts, src/main/resources/assets/admin/common/js/issue/event/IssueServerEvent.ts
- Changes in backend to move comments out of issues and store them under /issues/issue-X/comment-Y
=> Backend changes to comments

src/main/resources/assets/admin/common/js/ui/selector/list/ListBox.ts
… unchecked in the options-list #351
=> Enable suppressing of notification after removing items from ListBox

src/main/resources/assets/admin/common/styles/apps/content/view/detail/widget-view.less
Added color mixin for content status classes in widgets.
=> Details Panel - Content status is not styled according to the rules #359

README.md, build.gradle, gulpfile.js
* Added support for the `env` variable.
* Removed shared files from copying into the `.jar`.
* Added `npmInstallForce` task to forcefully update all packages to the newer versions.
* Added error logging, while processing `.less` files.
* Added build failure on LESS error.
* Added documentation.
=> Optimize the production build #305

src/main/resources/assets/admin/common/js/app/ServerEventsConnection.ts, src/main/resources/assets/admin/common/js/content/event/RepositoryEvent.ts, src/main/resources/assets/admin/common/js/content/event/_module.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
Added Repository event with handler.
Fixed `TreeGrid` highlighted node update, when the grid is reloaded.
=> Repository server events are not handled #383

src/main/resources/assets/admin/common/js/ui/dialog/ProgressBarManager.ts
=> Show notification of correct type based on response from task progress API

src/main/resources/assets/admin/common/js/content/site/inputtype/siteconfigurator/SiteConfiguratorDialog.ts, src/main/resources/assets/admin/common/js/ui/dialog/ConfirmationDialog.ts, src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts, src/main/resources/assets/admin/common/js/ui/grid/Grid.ts, src/main/resources/assets/admin/common/js/util/htmlarea/dialog/ModalDialog.ts, src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less
…able, when the area is switched to 'full screen' #436
=> Refactor positioning of modal dialog

src/main/resources/assets/admin/common/js/content/order/ChildOrder.ts, src/main/resources/assets/admin/common/js/content/util/ContentRowFormatter.ts, src/main/resources/assets/admin/common/js/query/QueryField.ts
Added child order by `publish.from`.
=> Sort content dialog - Add an option to sort by Published date #454

src/main/resources/assets/admin/common/js/ui/Viewer.ts, src/main/resources/assets/admin/common/js/ui/security/PrincipalComboBox.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts, src/main/resources/assets/admin/common/styles/api/ui/selector/combobox/selected-options.less, src/main/resources/assets/admin/common/styles/api/ui/text/inplace-text-input.less
=> Hide edit and remove icons in readonly viewer

src/main/resources/assets/admin/common/js/ui/tab/TabItem.ts, src/main/resources/assets/admin/common/js/ui/tab/TabMenu.ts, src/main/resources/assets/admin/common/js/ui/tab/TabMenuButton.ts, src/main/resources/assets/admin/common/styles/api/app/sort-content-dialog.less
Added customization of the TabMenu.
=> Implement new dropdown control for sorting dialog #479

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/ImageModalDialogCKE.ts, src/main/resources/assets/admin/common/lib/ckeditor/plugins/image2/plugin.js
-updated image plugin to enable justify button on toolbar
=> CKEditor: image justify alignment not working #536

src/main/resources/assets/admin/common/js/form/inputtype/text/HtmlAreaCK.ts, src/main/resources/assets/admin/common/styles/api/util/htmlarea/html-editor.less
-Updates: don't shrink editor on blur
=> CKEditor: shrink editor on blur #548

src/main/resources/assets/admin/common/js/ui/selector/list/ListBox.ts
…en, when the issue is closed #585
=> Implement setReadOnly method in ListBox class

src/main/resources/assets/admin/common/js/dom/ElementHelper.ts, src/main/resources/assets/admin/common/js/dom/InputEl.ts, src/main/resources/assets/admin/common/js/form/inputtype/number/Double.ts, src/main/resources/assets/admin/common/js/form/inputtype/number/Long.ts, src/main/resources/assets/admin/common/js/form/inputtype/text/TextLine.ts, src/main/resources/assets/admin/common/js/ui/text/AutosizeTextInput.ts, src/main/resources/assets/admin/common/js/ui/text/EmailInput.ts
Disabled autocomplete in the inputs, except inputs without controls.
=> Autocomplete should be turned off in all input fields #595

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
=> Expose Cancel button in ModalDialog class

src/main/resources/assets/admin/common/js/app/wizard/WizardPanel.ts, src/main/resources/assets/admin/common/js/app/wizard/WizardStepNavigatorAndToolbar.ts, src/main/resources/assets/admin/common/styles/api/app/wizard/wizard-step-navigator-and-toolbar.less
* Fixed handling of the toolbar and navigator, when the wizard is minimized.
* Refactored step navigator.
=> Wizard Step navigator is partially visible in collapsed mode #643 

src/main/resources/assets/admin/common/js/util/htmlarea/dialog/ImageModalDialogCKE.ts, src/main/resources/assets/admin/common/js/util/htmlarea/editor/HTMLAreaBuilderCKE.ts, src/main/resources/assets/admin/common/lib/ckeditor/plugins/image2/plugin.js, src/main/resources/assets/admin/common/styles/api/util/htmlarea/html-editor.less
-updated image plugin code to set alignment styles same as for tinymce
=> CKE produces different HTML source when inserting images #665

src/main/resources/assets/admin/common/js/ui/selector/DropdownGrid.ts, src/main/resources/assets/admin/common/js/ui/selector/DropdownList.ts, src/main/resources/assets/admin/common/js/ui/selector/DropdownTreeGrid.ts, src/main/resources/assets/admin/common/js/ui/selector/OptionsTreeGrid.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeNode.ts
=> Options inside content selector are not refreshed on content update

src/main/resources/assets/admin/common/js/app/NavigatedAppPanel.ts, src/main/resources/assets/admin/common/js/app/_module.ts, src/main/resources/assets/admin/common/js/ui/button/CycleButton.ts, src/main/resources/assets/admin/common/js/ui/button/_module.ts, src/main/resources/assets/admin/common/styles/api/app/navigated-panel.less, src/main/resources/assets/admin/common/styles/api/ui/button/cycle-button.less, src/main/resources/assets/admin/common/styles/styles.less
Restored CycleButton and NavigatedAppPanel classes and styles.
=> Move remaining classes and styles #730

src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
=> Browser console errors when dragging HTML Area inside an ItemSet #759

src/main/resources/assets/admin/common/js/dom/FormInputEl.ts
…ontent and x-data is included #778
=> X-data steps in the Wizard toolbar are not refreshed when switching between content versions

src/main/resources/assets/admin/common/js/content/ContentSummary.ts, src/main/resources/assets/admin/common/js/content/ContentSummaryAndCompareStatus.ts, src/main/resources/assets/admin/common/js/content/query/ContentQuery.ts
=> Refactor isReferencedBy method in ContentSummary

src/main/resources/assets/admin/common/js/ui/dialog/ProgressBarManager.ts
-There's one issue to consider regarding using task events for progress bar manager:
we submit task (send a request to backend) and wait for task id to be returned, however task might complete before we receive task id and start listening for task events; Currently this is handled by sending request (when task id is received) to fetch task state
=> Change ProgressBarManager to use TaskEvent #821

src/main/resources/assets/admin/common/js/application/ApplicationInstallResult.ts, src/main/resources/assets/admin/common/js/application/InstallUrlApplicationRequest.ts, src/main/resources/assets/admin/common/js/application/ListMarketApplicationsRequest.ts, src/main/resources/assets/admin/common/js/application/MarketApplication.ts, src/main/resources/assets/admin/common/js/application/MarketApplicationMetadata.ts, src/main/resources/assets/admin/common/js/application/MarketApplicationResponse.ts, src/main/resources/assets/admin/common/js/application/MarketHelper.ts, src/main/resources/assets/admin/common/js/application/_module.ts, src/main/resources/assets/admin/common/js/application/json/ApplicationInstallResultJson.ts, src/main/resources/assets/admin/common/js/application/json/MarketApplicationJson.ts, src/main/resources/assets/admin/common/js/application/json/MarketApplicationsListJson.ts, src/main/resources/assets/admin/common/js/application/json/_module.ts
=> Move market API to lib-admin-ui #831

src/main/resources/assets/admin/common/js/event/ServerEventsConnection.ts, src/main/resources/assets/admin/common/js/event/ServerEventsListener.ts
…or deleted in another browser-window #852
-Have to update server events listener to receive report events
=> Handle unknown server events

src/main/resources/assets/admin/common/js/aggregation/BucketAggregationView.ts, src/main/resources/assets/admin/common/js/aggregation/BucketView.ts
…#863
Changes reqired for https://github.com/enonic/app-contentstudio/issues/490 to work
=> Support preselect in BucketView

src/main/resources/assets/admin/common/js/app/bar/AppBarTabMenuItem.ts
=> Implement methods for disabling/enabling the close icon in menu bar tabs

src/main/resources/assets/admin/common/js/data/PropertyArray.ts, src/main/resources/assets/admin/common/js/form/inputtype/checkbox/Checkbox.ts
…isabled after publishing in another tab #878
=> Enable clearing property array and resetting checkbox property value

src/main/resources/assets/admin/common/js/form/FormItemOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts, src/main/resources/assets/admin/common/js/form/FormItemView.ts, src/main/resources/assets/admin/common/js/form/FormOccurrenceDraggableLabel.ts, src/main/resources/assets/admin/common/js/form/InputView.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/FormSetView.ts, src/main/resources/i18n/common.properties, src/main/resources/i18n/common_ru.properties
-Reworked FormSetOccurrenceView to correctly check it's properties are dirty
-added hasNonDefaultValues() method in item view and occurrences view classes to check if there are non empty/non default values in form items to trigger confirmation dialog in case when occurrence removed
=> Ask for confirmation when deleting existing item/option-set #903

src/main/resources/assets/admin/common/js/ui/menu/TreeContextMenu.ts
* Added "expand" listener.
* Refactored `addAction`.
=> Implement onItemExpanded event handling in TreeContextMenu

src/main/resources/assets/admin/common/js/ui/menu/TreeContextMenu.ts
Updated the check, before triggering the expand event.
=> Implement onItemExpanded event handling in TreeContextMenu #949

src/main/resources/assets/admin/common/js/ui/selector/list/ListBox.ts
-Added sorting functionality for item views in listbox
=> Support sorting in ListBox class

src/main/resources/assets/admin/common/js/data/PropertySet.ts
=> Enable getting property arrays in PropertySet

src/main/resources/assets/admin/common/js/data/PropertySet.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
* Added method to remove empty property sets.
=> ID Provider Config - Optional item set storage #962

src/main/resources/assets/admin/common/lib/slickgrid/lib/jquery.event.drag-2.3.js, src/main/resources/assets/admin/common/lib/slickgrid/slick.grid.js
-Small issue with syntax that is huge problem for IE (but not other browsers)
=> Launcher Panel does not load in MS Edge #975

src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts
… in Component View #985
-Totally IE issue, devs have already encountered same/similar behaviour
=> [MS IE] Unable to type search text in the combobox input field

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
-Option items container was not shown when needed on FormOptionSetOptionView update
-small refactoring
=> Option form is not displayed after rollback a version #989

src/main/resources/assets/admin/common/js/dom/IFrameEl.ts
…ent in wizard or version rollback #987
=> Refresh iFrame element whenever its URL changes

src/main/resources/assets/admin/common/js/application/Application.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
…r starting 2 selected applications #1004
Need to update treegrid to complete https://github.com/enonic/app-applications/issues/94
=> Notify about data refresh after fetching tree nodes

src/main/resources/assets/admin/common/js/content/ContentPath.ts
-Issue with ContentPath constructing from string
=> Application that creates content on init causes console errors #1018

src/main/resources/assets/admin/common/js/data/PropertySet.ts
=> Implement a method to sync empty arrays in a property set

src/main/resources/assets/admin/common/js/ui/uploader/UploaderEl.ts
-Replacing  '/', '*', '?', '|', ':' with underscore '_'
=> Sanitize binary names #1010

src/main/resources/assets/admin/common/js/form/FormItemOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/FormItemOccurrences.ts, src/main/resources/assets/admin/common/js/form/FormItemView.ts, src/main/resources/assets/admin/common/js/form/InputView.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/FormSetView.ts, src/main/resources/assets/admin/common/js/form/set/fieldset/FieldSetView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts, src/main/resources/assets/admin/common/js/ui/dialog/NotificationDialog.ts, src/main/resources/assets/admin/common/js/ui/dialog/_module.ts, src/main/resources/i18n/common.properties, src/main/resources/i18n/common_ru.properties
-Showing notification message in dialog if deselected option item has any form item non-empty
=> Confirm clearing the form on deselecting an option in an OptionSet

src/main/resources/assets/admin/common/js/content/Workflow.ts, src/main/resources/assets/admin/common/js/content/json/WorkflowJson.ts, src/main/resources/assets/spec/common/content/ContentSummary.spec.ts
Requires this to work:
https://github.com/enonic/xp/pull/7209
=> Implement "Mark as Ready" action #1032

src/main/resources/assets/admin/common/lib/slickgrid/slick.grid.js
-Updating slickgrid removed all our custom gallery mode logic, brought it back
=> Incorrect layout inside image selector dropdown #1031

src/main/resources/assets/admin/common/js/ui/tab/TabMenu.ts
Updated methods access for better inheritance options.
=> Display issue type icon in the details dialog #1037

src/main/resources/assets/admin/common/js/content/ContentSummary.ts, src/main/resources/assets/admin/common/js/content/json/ContentSummaryJson.ts, src/main/resources/assets/spec/common/content/ContentSummary.spec.ts
-Adding inherited field to a ContentSummary
=> Add `inherited` property to Content Summary

src/main/resources/assets/admin/common/js/rest/JsonRequest.ts, src/main/resources/assets/admin/common/js/rest/ResourceRequest.ts
-Update request classes to allow sending FormData for multipart rest endpoints
=> Implement New Layer modal dialog #1051

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
=> Add unsubscribe method for the close button in ModalDialog class

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts, src/main/resources/assets/admin/common/js/util/AppHelper.ts
* Added new debounce function, that will be called immediately and after some timeout, if it was called at least once during that interval.
* Updated ModalDialog resize handler to be called just in time, without some delay.
=> Create Issue dialog - hide a vertical scroll bar when not needed #1064

build.gradle, gulpfile.js, package-lock.json, package.json, src/main/resources/assets/admin/common/js/ui/locale/Flag.ts, src/main/resources/assets/admin/common/js/ui/locale/LocaleComboBox.ts, src/main/resources/assets/admin/common/js/ui/locale/LocaleViewer.ts, src/main/resources/assets/admin/common/js/ui/locale/_module.ts, src/main/resources/assets/admin/common/styles/_module.less, src/main/resources/assets/admin/common/styles/api/ui/locale/flag.less, src/main/resources/assets/admin/common/styles/api/ui/locale/locale-combobox.less, src/main/resources/assets/admin/common/styles/api/ui/locale/locale-selected-option-view.less, src/main/resources/assets/admin/common/styles/api/ui/locale/locale-viewer.less, src/main/resources/assets/admin/common/styles/styles.less
* Updated Locale selector styling by adding the flag icon.
=> Show flag icons in the Language selector #1066

src/main/resources/assets/admin/common/js/ui/locale/Flag.ts, src/main/resources/assets/admin/common/styles/api/ui/locale/flag.less
Updated Flag to be able to inherit from it.
=> Fixes for the icon selector in the layer dialog #1068

src/main/resources/assets/admin/common/js/ui/locale/Flag.ts, src/main/resources/assets/admin/common/styles/api/ui/locale/flag.less
Updated language code mappings.
=> Fix mapping of flag icons and languages #1070

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts, src/main/resources/assets/admin/common/js/util/AppHelper.ts
Fixed `runOnceAndDebounce`, calling function at the end of the timeout, if it was called at least once during the debounce interval.
=> Broken layout in modal dailogs #1072

src/main/resources/assets/admin/common/js/ui/selector/combobox/RichComboBox.ts
…ped in the filter options input #1107
=> Filtering doesn't work in descriptor selectors

src/main/resources/assets/admin/common/js/ui/selector/DropdownTreeGrid.ts
-Reverting changes made in https://github.com/enonic/lib-admin-ui/issues/1132,
have to solve issue with cycled postLoad() with different approach because this one breaks combobox
=> Error after selecting an option in Image Selector #1146

src/main/resources/assets/admin/common/js/ui/selector/DropdownGrid.ts, src/main/resources/assets/admin/common/js/ui/selector/DropdownList.ts
-Hiding grid when not using it to disable postload
=> Error after selecting an option in Image Selector #1136

src/main/resources/assets/admin/common/lib/slickgrid/slick.grid.js
…rator. #1154
-Incorrectly calculated gallery row height
=> Incorrect calculation of gallery row height in Image selector

package-lock.json, package.json, src/main/resources/assets/admin/common/js/app/view/ItemDataGroup.ts, src/main/resources/assets/admin/common/js/application/MarketApplication.ts, src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts, src/main/resources/assets/admin/common/js/form/set/FormSetView.ts, src/main/resources/assets/admin/common/js/notify/NotificationMessage.ts, src/main/resources/assets/admin/common/js/notify/NotifyOpts.ts, src/main/resources/assets/admin/common/js/ui/DragHelper.ts, src/main/resources/assets/admin/common/js/ui/button/ActionButton.ts, src/main/resources/assets/admin/common/js/ui/button/Button.ts, src/main/resources/assets/admin/common/js/ui/menu/MenuItem.ts, src/main/resources/assets/admin/common/js/util/Messages.ts, src/main/resources/assets/admin/common/js/validator/Validator.ts, tsconfig.json
Removed HTML from the label, that should be a string.
Added listeners for icon class change.
=> Always escape strings passed to setHtml()

src/main/resources/assets/admin/common/js/ui/KeyHelper.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts
…shift, meta etc.) #1161
-Replaced usage of deprecated 'which' property of KeyboardEvent with 'key', 'shiftKey', 'ctrlKey', 'altKey' and 'metaKey' properties, that also solved issue with dropdown shown when those keys pressed together with regular alphanumeric chars
=> Replace usage of deprecated 'which' property of KeyboardEvent

src/main/resources/assets/admin/common/js/form/inputtype/principal/PrincipalSelector.ts
-Typo in PrincipalSelector in config reader
=> Principal Selector - No filtering of principal type #1168

src/main/resources/assets/admin/common/js/dom/WindowDOM.ts
Fixed the shared Window instance.
=> Confirmation in the Wizard when there are no new changes #1173

src/main/resources/assets/admin/common/js/ui/uploader/UploaderEl.ts
…ontent type #1175
-Input types can limit occurrences of items, however uploader is not checking how many items we're uploading and we might upload more items than input allows
-Added mechanism for uploader that checks on demand if item to be uploaded (have to return 'false' from FineUploader's sumbitCallback to reject)
=> Enable limiting number of uploads in the Uploader element

src/main/resources/i18n/common_es.properties
Also updated some wrong translation
=> Translated the file

src/main/resources/i18n/common_pl.properties
=> #1100 added missing Polish phrases + some new lines

src/main/resources/assets/admin/common/js/ui/uploader/UploaderEl.ts
Added reset of the `overflow` property for the dropzone element.
Added drag event listeners for the dropzones, since default library does not allows adding custom listeners.
=> Dropzone in UploaderEl does not disappear #1183

src/main/resources/assets/admin/common/js/dom/Element.ts, src/main/resources/assets/admin/common/js/ui/grid/GridDragHandler.ts, src/main/resources/assets/admin/common/js/ui/selector/OptionsTreeGrid.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
=> Validate and escape all unsafe data passed to fromString method

package-lock.json, src/main/resources/assets/admin/common/js/data/ValueTypeBoolean.ts, src/main/resources/assets/admin/common/js/form/inputtype/checkbox/Checkbox.ts, src/main/resources/assets/admin/common/js/ui/Checkbox.ts, src/main/resources/assets/admin/common/js/ui/RadioGroup.ts
…ing property value. Changed default value of a boolean value type to false instead of null. Removed onChange event handlers of Checkbox and Radiogroup inputs since they are doing the same as FormInputEl's onChange handler (#1203)
=> Save button remains enabled after checkbox state is changed and content is saved

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrences.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetView.ts
-added lazy render handling for option set
=> Option-set inside part config is not shown in the Inspection panel #1206

src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less, src/main/resources/assets/admin/common/styles/global.less
-Using modal dialog's z-index (stored in admin artifacts npm module); if need to change it with relation to launcher then it is better to update it in admin artifacts module
-blurring and lowering z-index for launcher button when dialog is open
=> Notification message is covered by dialog #1223

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeRoot.ts
-handling selection change in one place
=> Browse toolbar is not updated after deleting content #1260

src/main/resources/assets/admin/common/js/ui/treegrid/TreeGrid.ts
-Dragged node's parent is calculated incorrectly
=> TreeGrid - dragged node disappears after DnD #1276

src/main/resources/i18n/common_ru.properties
This pull request was initiated by Lokalise (user Alan Semenov) at 2020-05-25 12:29:02
=> New translations in Russian

src/main/resources/assets/admin/common/js/dom/Body.ts, src/main/resources/assets/admin/common/styles/api/ui/dialog/modal-dialog.less
-Modal dialog is not working well with flex things, updating some flex css to make it work
=> [IE11] Incorrect content overflow in modal dialogs #1301

src/main/resources/i18n/common_no.properties
This pull request was initiated by Lokalise (user Jørgen Sivesind) at 2020-05-25 11:26:45
=> New translations in Norwegian

src/main/resources/assets/admin/common/js/app/bar/AppBar.ts, src/main/resources/assets/admin/common/js/app/bar/AppIcon.ts
* Moved `AppIcon` to the separate file;
* Refactored the rendering and initialization process.
=> Update AppIcon class to be customizable #1341

src/main/resources/assets/admin/common/js/util/Messages.ts, src/main/resources/assets/admin/common/js/util/MessagesInitializer.ts
=> Revert "i18n api: let adding new messages entries without clearing list"

src/main/resources/assets/admin/common/js/ui/selector/dropdown/Dropdown.ts
-doing nothing when pressing enter with no options available
=> Incorrect handling of Enter key event in dropdown in OptionSet #1707

package-lock.json, src/main/resources/assets/admin/common/js/form/FormOccurrenceDraggableLabel.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts, src/main/resources/assets/admin/common/styles/api/form/set/form-set-view.less, src/main/resources/assets/admin/common/styles/api/form/set/optionset/form-option-set-view.less, src/main/resources/assets/admin/common/styles/api/ui/button/more-button.less, src/main/resources/assets/admin/common/styles/api/ui/dialog/confirmation-dialog.less
**NB:** Had to revert changes made in 3327dac89ef87a38b62aedc9911def81c1182d4a because that was an option ID which was saved to property set so label just could not be used there.
=> No reset function for single-select option-set #1685

package-lock.json, package.json, src/main/resources/assets/admin/common/js/dom/Element.ts, tsconfig.json
-Using DOMPurify lib for parsing html element from string https://github.com/cure53/DOMPurify to prevent xss attacks
=> Sanitise HTML created from a string

src/main/resources/assets/admin/common/js/dom/Element.ts, src/main/resources/assets/admin/common/js/form/FormOccurrenceDraggableLabel.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
-HtmlArea has markup html saved in a property that is not to be used as a label definitely, thus filtering potential label string from html tags
-Setting label via textContent property to prevent XSS
-Fixing small issue in Element.fromString
=> Option Set - labels should be sanitized #1751

src/main/resources/assets/admin/common/js/ui/selector/OptionsTreeGrid.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/ComboBox.ts
…selected option in another browser tab #1771
-Fixing update
=> Console error after selected content in selector gets updated on the server

src/main/resources/assets/admin/common/js/ui/selector/DropdownGrid.ts
-Syncing DropdownGrid's inheritors behaviour
=> DropdownGrid refactoring

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
-handling removing of empty selection  ('_selected' array and empty non selected props) right in option set
=> Move cleanup of option-set's unselected options to FormOptionSetOccurrenceView

src/main/resources/assets/admin/common/js/form/FormView.ts
-Adding whenLayoutFinished working same as whenRendered
=> FormView: add whenRendered analog for layout finished event #1937

src/main/resources/assets/admin/common/js/form/FormItemLayer.ts, src/main/resources/assets/admin/common/js/form/FormView.ts, src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts, src/main/resources/assets/admin/common/js/form/inputtype/support/InputOccurrenceView.ts
-Focus was set when layout func have not been finished yet
-FormItemLayer layout can not be treated as finished until form items are appended, currently items are appended only after parent item is rendered
=> Site Configurator Dialog - first field doesn't get focus #1987

src/main/resources/assets/admin/common/js/app/browse/BrowsePanel.ts, src/main/resources/assets/admin/common/js/app/wizard/WizardPanel.ts
-Set width ratio for data/context panel to 68/32 (was 62/38)
-Moved live panel related code out of the WizardPanel to the only place where it belongs - ContentWizardPanel
-Put WizardPanel's elements and listeners initialization into separate methods (Only items not dependant on data load)
=> Refactor WizardPanel

src/main/resources/assets/admin/common/styles/api/ui/names-and-icon-viewer.less
-Have to limit visibility and text trim on child elements rather then on parent item
=> Options are not fully shown in AccessSelector #1999

src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseRichComboBox.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionView.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts, src/main/resources/assets/admin/common/js/ui/selector/combobox/RichSelectedOptionView.ts, src/main/resources/assets/admin/common/styles/api/form/inputtype/appconfig/application-configurator.less
-differentiating between setting option readonly and changing it's editable removable props
-adding action buttons on demand
=> BaseSelectedOptionView: refactor #2037

src/main/resources/assets/admin/common/js/util/loader/ImageLoader.ts
=> ImageLoader class is broken

src/main/resources/assets/admin/common/js/dom/FormInputEl.ts
- bind listeners only once on added
=> RadioGroup loses selection on add/remove #2148

src/main/resources/assets/admin/common/js/NodePath.ts, src/main/resources/assets/admin/common/js/event/NodeServerChange.ts, src/main/resources/assets/admin/common/js/event/NodeServerChangeItem.ts, src/main/resources/assets/admin/common/js/rest/Path.ts, src/main/resources/assets/admin/common/js/rest/ResourceRequest.ts, src/main/resources/assets/admin/common/js/security/CheckEmailAvailabilityRequest.ts, src/main/resources/assets/admin/common/js/util/MessagesInitializer.ts
-Created NodePath object for node paths received from server events. It inherits from Path class that will keep common path behaviour
=> NodeServerChangeItem: translate string paths to objects #2172

src/main/resources/assets/admin/common/js/ui/panel/SplitPanel.ts, src/main/resources/assets/admin/common/js/ui/toolbar/Toolbar.ts
=> Toolbar: let actions manually fold/unfold #2284

src/main/resources/assets/admin/common/js/ui/panel/SplitPanel.ts
-Updated calculation of a second panel in a SplitPanel to work correct
-Removed redundant code regarding deciding panel
-Updated default sizes of panels
=> SplitPanel: update calc of hidden second panel #2304

src/main/resources/assets/admin/common/js/dom/Element.ts, src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts, src/main/resources/assets/admin/common/js/ui/button/MenuButton.ts, src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts, src/main/resources/assets/admin/common/js/util/AppHelper.ts, src/main/resources/assets/admin/common/styles/api/ui/dialog/dropdown-button-row.less
-AppHelper: set a last focused element in focusout callback
-ModalDialog:
1) Update list of tabbable items on show and when new elements added into a dialog
2) On focusout check correctly focus last or first tabbable
-MenuButton: define dropdown handle position (right or left) to correctly navigate through it
=> Implement configurable position of dropdown handler in MenuButton

src/main/resources/assets/admin/common/js/managedaction/ManagedActionManager.ts, src/main/resources/assets/admin/common/js/ui/treegrid/TreeGridSelection.ts
-flaw in a TreeGridSelection prevented detecting selection change
-small fix for ManagedActionManager to avoid NPE
=> Error after restoring filtered content #2347

src/main/resources/assets/admin/common/js/ui/dialog/ModalDialog.ts
-updating list of tabbable elements if can't find any visible and enabled item in the list of tabbable elements
-checking if losing focus to iframe that is located within dialog (html editor), otherwise bringing focus back
=> Console error in ModalDialog #2367

src/main/resources/assets/admin/common/js/form/Occurrences.ts, src/main/resources/assets/admin/common/js/form/inputtype/checkbox/Checkbox.ts
-if min occurrences is more than 0 then validating checkbox: is valid if checkbox is checked and not valid if opposite
=> Support required checkbox #2346

src/main/resources/assets/admin/common/js/form/inputtype/time/Time.ts, src/main/resources/assets/admin/common/js/ui/time/DatePickerPopup.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePicker.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePickerPopup.ts, src/main/resources/assets/admin/common/js/ui/time/Picker.ts, src/main/resources/assets/admin/common/js/ui/time/SelectedDateChangedEvent.ts, src/main/resources/assets/admin/common/js/ui/time/TimePicker.ts, src/main/resources/assets/admin/common/js/ui/time/TimePickerPopup.ts, src/main/resources/assets/admin/common/js/util/DateHelper.ts, src/main/resources/assets/admin/common/js/util/LocalDate.ts, src/main/resources/assets/admin/common/js/util/LocalTime.ts, src/main/resources/assets/admin/common/js/util/LongTimeHMS.ts, src/main/resources/assets/admin/common/js/util/TimeHM.ts, src/main/resources/assets/admin/common/js/util/TimeHMS.ts
=> Refactor DatePicker classes #2433

src/main/resources/assets/admin/common/js/form/inputtype/time/Date.ts, src/main/resources/assets/admin/common/js/form/inputtype/time/DateTime.ts, src/main/resources/assets/admin/common/js/form/inputtype/time/Time.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePicker.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePickerPopup.ts, src/main/resources/assets/admin/common/js/ui/time/Picker.ts, src/main/resources/assets/admin/common/styles/api/ui/time/date-time-picker.less, src/main/resources/i18n/common.properties
* Fixed DatePicker not closing dropdown on click when focused
* Refactored DateTime.createInputOccurrenceElement
* Fixed time not being set when setting default value
* Datepicker defaultButton
* Added a default button to the date picker popup
* DateTime picker set deault button
=> Date picker new Default button

src/main/resources/assets/admin/common/js/form/set/FormSetView.ts
https://api.jqueryui.com/sortable/#option-cancel
=> Added cancel prop to sortable of FormSetView (#2510)

src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
Correctly handle radio button value in a property set when generating a set title (#2546)
=> Radio button value should not be used for item-set label

src/main/resources/assets/admin/common/js/ui/selector/combobox/BaseSelectedOptionsView.ts, src/main/resources/i18n/common.properties
Also refactored `addOptions` method.
=> Changed truncated list message (#2572)

src/main/resources/assets/admin/common/js/aggregation/BucketAggregationView.ts, src/main/resources/assets/admin/common/js/aggregation/BucketsContainer.ts, src/main/resources/assets/admin/common/js/app/browse/filter/BrowseFilterPanel.ts, src/main/resources/assets/admin/common/styles/api/aggregation/buckets-container.less, src/main/resources/assets/admin/common/styles/main.less
-added container for buckets with toggler button to show more/less buckets
-filtering out buckets with zero doc count
=> Limit the list of filter options in each aggregation #2580

src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts
Check for instance type when trying to access getInputType method
=> Content Wizard form crashes while resolving item-set title

src/main/resources/assets/admin/common/js/ui/selector/list/ListBoxDropdown.ts, src/main/resources/assets/admin/common/js/ui/selector/list/SelectableListBoxDropdown.ts, src/main/resources/assets/admin/common/styles/api/aggregation/buckets-container.less, src/main/resources/assets/admin/common/styles/api/ui/selector/list/listbox-dropdown.less, src/main/resources/assets/admin/common/styles/api/ui/selector/list/selectable-listbox-dropdown.less
-aligned behaviour with combobox
=> SelectableListBoxDropdown: add keyboard navigation #2612

src/main/resources/assets/admin/common/js/ui/button/MenuButton.ts
Using this implementation in https://github.com/enonic/app-contentstudio/issues/4666
=> Implemented getMenuItems in MenuButton (#2628)

src/main/resources/assets/admin/common/js/ui/form/Validators.ts
Updated validators return type
=> Updated validators (#2667)

build.gradle
=> Upgrade build to allow skipping lint task in lib-admin-ui #2688

src/main/resources/assets/admin/common/js/ui/form/Validators.ts
-Adding updated validation to a 4.3 branch
=> Update validators #2667

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewSingleOption.ts
A different way to fix the problem as the previous one didn't do the trick.
=> Multiple occurrences of an option-set should not be auto-expanded

src/main/resources/assets/admin/common/js/form/inputtype/appconfig/ApplicationConfiguratorDialog.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrences.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
-Populating property array of a FormOptionSetOptionView with a default selected options on add
-Adjusted constructor props of ApplicationConfiguratorDialog
=> Preselection of options inside option-set doesn't work in site.xml #2797

src/main/resources/assets/admin/common/js/form/InputView.ts, src/main/resources/assets/admin/common/js/form/inputtype/checkbox/Checkbox.ts, src/main/resources/assets/admin/common/js/form/inputtype/combobox/ComboBox.ts, src/main/resources/assets/admin/common/js/form/inputtype/principal/PrincipalSelector.ts, src/main/resources/assets/admin/common/js/form/inputtype/radiobutton/RadioButton.ts, src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputType.ts, src/main/resources/assets/admin/common/js/form/set/FormSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceViewSingleOption.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
-removing validation results on clean
-stashing option set option's data on clean and reusing it if this option is selected again -clean up in FormSetOccurrenceView
=> FormItemView's clear function: add it to missing items #2871

src/main/resources/assets/admin/common/js/app/wizard/WizardHeaderWithDisplayNameAndName.ts
=> Refactor setName & setDisplayName in WizardHeaderWithDisplayNameAndName

build.gradle, package-lock.json, package.json
A quick fix for build optimization.
=> Add caching for copy tasks

src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOccurrenceView.ts, src/main/resources/assets/admin/common/js/form/set/optionset/FormOptionSetOptionView.ts
=> Multi-select option-set allows selecting more than maximum options #2942

src/main/resources/assets/admin/common/js/form/inputtype/text/TextInputType.ts
Test results: https://github.com/enonic/app-contentstudio/pull/5638
Just one test is failing, it's fix is in another pool: https://github.com/enonic/lib-admin-ui/pull/2944
=> Issues in option set with nested mixin #2947

src/main/resources/assets/admin/common/js/ui/form/Validators.ts
As requested, url path section now allow "," and "…"
=> Allow commas in path section of url #3125

src/main/resources/assets/admin/common/js/ui/form/Validators.ts
Needed for: https://github.com/enonic/app-contentstudio/issues/3574
=> New telephone validator #3169

src/main/resources/assets/admin/common/js/dom/ElementHelper.ts, src/main/resources/assets/admin/common/js/ui/Checkbox.ts, src/main/resources/assets/admin/common/styles/api/form-common.less, src/main/resources/assets/admin/common/styles/api/input-common.less, src/main/resources/assets/admin/common/styles/api/ui/checkbox.less, src/main/resources/assets/admin/common/styles/api/ui/toolbar.less, src/main/resources/assets/admin/common/styles/api/ui/uploader/uploader-el.less
Also fixed uploader styles to not use absolute positioning
=> Accessibility: Checkbox #3734

src/main/resources/assets/admin/common/js/ui/security/PrincipalComboBox.ts, src/main/resources/assets/admin/common/js/ui/selector/list/FilterableListBoxWrapper.ts, src/main/resources/assets/admin/common/js/ui/selector/list/TreeListBox.ts
TreeListBox: don't invoke lazy load on shown #3880
- Trigger load on first show when it is needed
=> TreeListBox: don't invoke lazy load on shown #3880

src/main/resources/assets/admin/common/js/ui/time/DatePickerPopup.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePicker.ts, src/main/resources/assets/admin/common/js/ui/time/DateTimePickerPopup.ts, src/main/resources/assets/admin/common/js/ui/time/TimePickerPopup.ts, src/main/resources/assets/admin/common/styles/api/ui/time/date-time-picker.less, src/main/resources/assets/admin/common/styles/mixins.less
=> Incorrect styles in TimePicker Popup

src/main/resources/assets/admin/common/js/form/inputtype/support/BaseInputTypeNotManagingAdd.ts
- don't update non-layouted inputs
=> Error appears after reverting content with text-area in x-data #3979

.swcrc, package-lock.json, package.json, src/main/resources/assets/admin/common/js/ui2/ActionButton.ts, src/main/resources/assets/admin/common/js/ui2/LegacyElement.ts, tsconfig.json, webpack.config.js
Added proper aliases for react, and replace renderer with react.
Upgraded `@enonic-ui` dependency.
=> Enonic UI: Fix rendering of components with hooks #4097
